### ISSUE TITLE
The latest upstream version of catalogItems_2022-04-01.json breaks the OpenApiParser

### ISSUE THREAD

**Issue by dpash** [jlevers/selling-partner-api#719]
I don't know if this is the best repository to open this issue, but the most recent change to catalogItems_2022-04-01.json causes the OpenApiParser to enter some kind of infinite loop and it never generates the code for for that API.

Reverting to the version two weeks ago works correctly but the current version does not. 

Good:

https://raw.githubusercontent.com/amzn/selling-partner-api-models/e475529b592fc9622fda5d0e357eddcb2f142c54/models/catalog-items-api-model/catalogItems_2022-04-01.json

Bad:

https://raw.githubusercontent.com/amzn/selling-partner-api-models/e475529b592fc9622fda5d0e357eddcb2f142c54/models/catalog-items-api-model/catalogItems_2022-04-01.json

Diff:

https://github.com/amzn/selling-partner-api-models/commit/f15a5da356295e04c2c186c6e7fc7e07ddd36085

Let me know if you'd prefer me to open this in the saloon-sdk-generator repo instead. If you have any ideas what might be causing this and can point me in the right direction, I can attempt to debug further

**Comment by jlevers** [comment]
Just to confirm, is this fixed by #727?

**Comment by dpash** [comment]
Sadly not. That was a fix for client users rather than during generation. I was hoping that the caching work on https://github.com/highsidelabs/saloon-sdk-generator/pull/6 would have fixed it, as that's a very similar symptom. Sadly I'm still experiencing the issue.

**Comment by jlevers** [comment]
My hunch is that there's a circular ref lookup happening somewhere, because I think I ran into this problem once before. I'll do some digging.

**Comment by dpash** [comment]
Yeah, I've been having a look through and what I've discovered is that `ItemBrowseClassifications` has a collection of `ItemBrowseClassificationsByMarketplace`s which has a `classifications` property which is an array of  `ItemBrowseClassifications`

**Comment by dpash** [comment]
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itembrowseclassifications and yes the documentation implies that's intentional
